window.BIXOS = [
  { id: 1, name: "Pequituxo", region: "Iniciais", images: [{ src: "assets/bixos/pequituxo-2-0.png", label: "Arte 2.0" }] },
  { id: 2, name: "Pequitaxo", region: "Iniciais", images: [{ src: "assets/bixos/pequitaxo.png", label: "Padrao" }] },
  { id: 3, name: "Pequiacu", displayName: "PequiaÃ§u", region: "Iniciais", images: [{ src: "assets/bixos/pequiacu.png", label: "Padrao" }] },
  { id: 4, name: "Lobareda", region: "Iniciais", images: [{ src: "assets/bixos/lobareda-2-0.png", label: "Arte 2.0" }] },
  { id: 5, name: "Loborralha", region: "Iniciais", images: [{ src: "assets/bixos/loborralha.png", label: "Padrao" }] },
  { id: 6, name: "Foguara", displayName: "FoguarÃ¡", region: "Iniciais", images: [{ src: "assets/bixos/foguara.png", label: "Padrao" }] },
  { id: 7, name: "Tracajato", region: "Iniciais", images: [{ src: "assets/bixos/tracajato-2-0.png", label: "Arte 2.0" }] },
  { id: 8, name: "Tigraroa", region: "Iniciais", images: [{ src: "assets/bixos/tigraroa.png", label: "Padrao" }] },
  { id: 9, name: "Chuvaruga", region: "Iniciais", images: [{ src: "assets/bixos/chuvaruga.png", label: "Padrao" }] },
  { id: 10, name: "Ratrovao", displayName: "RatrovÃ£o", region: "Primeiro Mato", images: [] },
  { id: 11, name: "Mucurraio", region: "Primeiro Mato", images: [] },
  { id: 12, name: "Larvinho", region: "Primeiro Mato", images: [] },
  { id: 13, name: "Cerasulo", region: "Primeiro Mato", images: [] },
  { id: 14, name: "Puabelha", displayName: "PuÃ¡belha", region: "Primeiro Mato", images: [] },
  { id: 15, name: "Espigueto", region: "Primeiro Mato", images: [] },
  { id: 16, name: "Carnibondo", region: "Primeiro Mato", images: [] },
  { id: 17, name: "Cabaducao", displayName: "CabaducÃ£o", region: "Primeiro Mato", images: [] },
  { id: 18, name: "Cuticutia", region: "Primeiro Mato", images: [] },
  { id: 19, name: "Capivari", region: "Primeiro Mato", images: [] },
  { id: 20, name: "Anin", region: "Primeiro Mato", images: [] },
  { id: 21, name: "Escuranu", region: "Primeiro Mato", images: [] },
  { id: 22, name: "Claranu", region: "Primeiro Mato", images: [] },
  { id: 23, name: "Pebatu", region: "Cavernas", images: [] },
  { id: 24, name: "Tacanastra", region: "Cavernas", images: [] },
  { id: 25, name: "Barrin", region: "Cavernas", images: [] },
  { id: 26, name: "Barruja", region: "Cavernas", images: [] },
  { id: 27, name: "Preda", region: "Cavernas", images: [] },
  { id: 28, name: "Esmeraldita", region: "Cavernas", images: [] },
  { id: 29, name: "Cristaralda", region: "Cavernas", images: [] },
  { id: 30, name: "Mirimin", region: "Matos Intermediários", images: [] },
  { id: 31, name: "Banderua", displayName: "BanderuÃ¡", region: "Matos Intermediários", images: [] },
  { id: 32, name: "Vermaligno", region: "Matos Intermediários", images: [] },
  { id: 33, name: "Furtapupa", region: "Matos Intermediários", images: [] },
  { id: 34, name: "Ladrabelha", region: "Matos Intermediários", images: [] },
  { id: 35, name: "Ladrabelha RAINHA", region: "Matos Intermediários", images: [] },
  { id: 36, name: "Fumiga", region: "Matos Intermediários", images: [] },
  { id: 37, name: "Fogomiga", region: "Matos Intermediários", images: [] },
  { id: 38, name: "Sauvardente", displayName: "SaÃºvardente", region: "Matos Intermediários", images: [] },
  { id: 39, name: "Gongacu", displayName: "GongaÃ§u", region: "Matos Intermediários", images: [] },
  { id: 40, name: "Garapaca", displayName: "GarapaÃ§a", region: "Matos Intermediários", images: [] },
  { id: 41, name: "Gonglutao", displayName: "GonglutÃ£o", region: "Matos Intermediários", images: [] },
  { id: 42, name: "Venenanta", region: "Matos Intermediários", images: [] },
  { id: 43, name: "Peconhanta", displayName: "PeÃ§onhanta", region: "Matos Intermediários", images: [] },
  { id: 44, name: "Castain", displayName: "CastaÃ­n", region: "Matos Intermediários", images: [] },
  { id: 45, name: "Juica", displayName: "JuÃ­ca", region: "Matos Intermediários", images: [] },
  { id: 46, name: "Cajumbo", region: "Matos Intermediários", images: [] },
  { id: 47, name: "Florota", region: "Matos Intermediários", images: [] },
  { id: 48, name: "Favagem", region: "Matos Intermediários", images: [] },
  { id: 49, name: "Bolotoco", region: "Matos Intermediários", images: [] },
  { id: 50, name: "Pregaco", region: "Matos Intermediários", images: [] },
  { id: 51, name: "Ferrugio", region: "Matos Intermediários", images: [] },
  { id: 52, name: "Maragatin", region: "Matos Intermediários", images: [] },
  { id: 53, name: "Sombronca", displayName: "SombronÃ§a", region: "Matos Intermediários", images: [] },
  { id: 54, name: "Pontapiu", region: "Matos Intermediários", images: [] },
  { id: 55, name: "Repeteu", displayName: "RepetÃ©u", region: "Matos Intermediários", images: [] },
  { id: 56, name: "Seripeia", displayName: "SeripÃªia", region: "Matos Intermediários", images: [] },
  { id: 57, name: "Catitin", region: "Matos Intermediários", images: [] },
  { id: 58, name: "Ardentu", region: "Matos Intermediários", images: [] },
  { id: 59, name: "Vulcanodonte", region: "Matos Intermediários", images: [] },
  { id: 60, name: "Ignodonte", region: "Matos Intermediários", images: [] },
  { id: 61, name: "Javaligneo", displayName: "JavalÃ­gneo", region: "Matos Intermediários", images: [] },
  { id: 62, name: "Piapa", region: "Águas", images: [] },
  { id: 63, name: "Flapiau", region: "Águas", images: [] },
  { id: 64, name: "Trucunare", displayName: "TrucunarÃ©", region: "Águas", images: [] },
  { id: 65, name: "Paku", region: "Águas", images: [] },
  { id: 66, name: "Tambakao", displayName: "TambakÃ£o", region: "Águas", images: [] },
  { id: 67, name: "Tapetin", region: "Águas", images: [] },
  { id: 68, name: "Ferraiada", region: "Águas", images: [] },
  { id: 69, name: "Gelarraia", region: "Águas", images: [] },
  { id: 70, name: "Brasarraia", region: "Águas", images: [] },
  { id: 71, name: "Mandin", region: "Águas", images: [] },
  { id: 72, name: "Kascudo", region: "Águas", images: [] },
  { id: 73, name: "Kuiukari", region: "Águas", images: [] },
  { id: 74, name: "Piranhac", region: "Águas", images: [] },
  { id: 75, name: "Piranhalma", region: "Águas", images: [] },
  { id: 76, name: "Arironda", region: "Águas", images: [] },
  { id: 77, name: "Feraranha", region: "Águas", images: [] },
  { id: 78, name: "Faiscaru", displayName: "FaÃ­scaru", region: "Águas", images: [] },
  { id: 79, name: "Amporaque", displayName: "AmporaquÃª", region: "Águas", images: [] },
  { id: 80, name: "Piraruchoque", region: "Águas", images: [] },
  { id: 81, name: "Anfiboto", region: "Águas", images: [] },
  { id: 82, name: "Botolado", region: "Águas", images: [] },
  { id: 83, name: "Xoko", region: "Aldeias", images: [] },
  { id: 84, name: "Muirakira", displayName: "MuirakirÃ£", region: "Aldeias", images: [] },
  { id: 85, name: "Xamonca", displayName: "XamÃµnÃ§a", region: "Aldeias", images: [] },
  { id: 86, name: "Bizerro", region: "Fazenda", images: [] },
  { id: 87, name: "Nelotauro", region: "Fazenda", images: [] },
  { id: 88, name: "Kitnetin", region: "Fazenda", images: [] },
  { id: 89, name: "Fortalezim", region: "Fazenda", images: [] },
  { id: 90, name: "Capotin", region: "Fazenda", images: [] },
  { id: 91, name: "Angolinha", region: "Fazenda", images: [] },
  { id: 92, name: "Jabutinga", region: "Fazenda", images: [] },
  { id: 93, name: "Jabutiranga", region: "Fazenda", images: [] },
  { id: 94, name: "Jabuterico", displayName: "JabutÃ©rico", region: "Fazenda", images: [] },
  { id: 95, name: "Chocaca", region: "Fazenda", images: [] },
  { id: 96, name: "Curicarga", region: "Fazenda", images: [] },
  { id: 97, name: "Pinti", region: "Fazenda", images: [] },
  { id: 98, name: "Raiomelo", region: "Fazenda", images: [] },
  { id: 99, name: "Trintagua", displayName: "TrintÃ¡gua", region: "Praia", images: [] },
  { id: 100, name: "Bigualhao", displayName: "BiguÃ¡lhÃ£o", region: "Praia", images: [] },
  { id: 101, name: "Sacolina", region: "Praia", images: [{ src: "assets/bixos/sacolina.png", label: "Padrao" }] },
  { id: 102, name: "Xorumina", region: "Praia", images: [{ src: "assets/bixos/xorumina.png", label: "Padrao" }] },
  { id: 103, name: "Grumerua", displayName: "GrumeruÃ¡", region: "Praia", images: [] },
  { id: 104, name: "Almirujo", region: "Praia", images: [] },
  { id: 105, name: "Jare", displayName: "JarÃ©", region: "Praia", images: [] },
  { id: 106, name: "Jaguape", displayName: "JaguapÃ©", region: "Praia", images: [] },
  { id: 107, name: "Cucare", displayName: "CucarÃ©", region: "Praia", images: [] },
  { id: 108, name: "Girinocaute", region: "Capital", images: [] },
  { id: 109, name: "Jiu-jia", region: "Capital", images: [] },
  { id: 110, name: "Curujudo", displayName: "CurujudÃ´", region: "Capital", images: [] },
  { id: 111, name: "Postenebroso", region: "Capital", images: [] },
  { id: 112, name: "Amaldicionado", region: "Capital", images: [] },
  { id: 113, name: "Bixanin", region: "Capital", images: [] },
  { id: 114, name: "Gaturno", region: "Capital", images: [] },
  { id: 115, name: "Piquirito", region: "Capital", images: [] },
  { id: 116, name: "Paguaio", region: "Capital", images: [] },
  { id: 117, name: "Ararande", displayName: "ArarandÃ©", region: "Capital", images: [] },
  { id: 118, name: "Rupiara", displayName: "RupiarÃ¡", region: "Capital", images: [] },
  { id: 119, name: "Rapinara", displayName: "RapinarÃ¡", region: "Capital", images: [] },
  { id: 120, name: "Marifecha", region: "Capital", images: [] },
  { id: 121, name: "Malicirosa", displayName: "MalÃ­cirosa", region: "Capital", images: [] },
  { id: 122, name: "Carimbela", region: "Capital", images: [] },
  { id: 123, name: "Sementilho", region: "Capital", images: [] },
  { id: 124, name: "Florempirea", displayName: "FlorempÃ­rea", region: "Capital", images: [] },
  { id: 125, name: "Dracoflora", region: "Capital", images: [] },
  { id: 126, name: "Duendussu", region: "Distrito", images: [
    { src: "assets/bixos/duendussu-padrao.png", label: "Padrao" },
    { src: "assets/bixos/duendussu-amarelo.png", label: "Amarelo" },
    { src: "assets/bixos/duendussu-azul.png", label: "Azul" },
    { src: "assets/bixos/duendussu-verde.png", label: "Verde" }
  ] },
  { id: 127, name: "Osglacial", region: "Distrito", images: [] },
  { id: 128, name: "Frigiguana", region: "Distrito", images: [] },
  { id: 129, name: "Aranguejeira", region: "Safari", images: [{ src: "assets/bixos/aranguejera.png", label: "Padrao" }] },
  { id: 130, name: "Armaderanha", region: "Safari", images: [{ src: "assets/bixos/armaderanha.png", label: "Padrao" }] },
  { id: 131, name: "Emo", region: "Safari", images: [] },
  { id: 132, name: "Ipema", displayName: "IpÃªma", region: "Safari", images: [
    { src: "assets/bixos/ipema-verde.png", label: "Verde" },
    { src: "assets/bixos/ipema-amarela.png", label: "Amarela" },
    { src: "assets/bixos/ipema-branca.png", label: "Branca" },
    { src: "assets/bixos/ipema-rosa.png", label: "Rosa" },
    { src: "assets/bixos/ipema-roxa.png", label: "Roxa" },
    { src: "assets/bixos/ipema-shiny.png", label: "Shiny" },
    { src: "assets/bixos/ipema-gif.gif", label: "Animada" }
  ] },
  { id: 133, name: "Zoco", displayName: "ZocÃ³", region: "Safari", images: [] },
  { id: 134, name: "Garcentelha", displayName: "GarÃ§entelha", region: "Safari", images: [] },
  { id: 135, name: "Hipnoguio", region: "Safari", images: [] },
  { id: 136, name: "Psicara", displayName: "PsicarÃ¡", region: "Safari", images: [] },
  { id: 137, name: "Douracapim", region: "Safari", images: [] },
  { id: 138, name: "Apanhadouro", region: "Safari", images: [] },
  { id: 139, name: "Solamigo", region: "Safari", images: [{ src: "assets/bixos/solamigo.png", label: "Padrao" }] },
  { id: 140, name: "Biquente", region: "Safari", images: [] },
  { id: 141, name: "Picapow", region: "Safari", images: [] },
  { id: 142, name: "Brocalgoz", region: "Safari", images: [] },
  { id: 143, name: "Mandioka", region: "Cidade Pequena/Mediana", images: [] },
  { id: 144, name: "Fritaoka", region: "Cidade Pequena/Mediana", images: [] },
  { id: 145, name: "Cozidoka", region: "Cidade Pequena/Mediana", images: [] },
  { id: 146, name: "Muskito", region: "Cidade Pequena/Mediana", images: [] },
  { id: 147, name: "Carapanaca", region: "Cidade Pequena/Mediana", images: [] },
  { id: 148, name: "Muricoca", displayName: "MuricoÃ§a", region: "Cidade Pequena/Mediana", images: [] },
  { id: 149, name: "Cako", region: "Cidade Pequena/Mediana", images: [] },
  { id: 150, name: "Simbolarta", region: "Cidade Fantasma", images: [] },
  { id: 151, name: "Mascaralida", displayName: "MascarÃ¡lida", region: "Cidade Fantasma", images: [] },
  { id: 152, name: "Borbocular", region: "Cidade Fantasma", images: [] },
  { id: 153, name: "Folhuru", region: "Cidade Fantasma", images: [] },
  { id: 154, name: "Bruxutau", region: "Cidade Fantasma", images: [] },
  { id: 155, name: "Matiperera", region: "Cidade Fantasma", images: [] },
  { id: 156, name: "Calangotico", displayName: "CalangÃ³tico", region: "Cidade Fantasma", images: [] },
  { id: 157, name: "Horripilango", region: "Cidade Fantasma", images: [] },
  { id: 158, name: "Sustoiu", displayName: "SustoiÃº", region: "Cidade Fantasma", images: [] },
  { id: 159, name: "Murrin", region: "Serra", images: [] },
  { id: 160, name: "Pancadon", region: "Serra", images: [] },
  { id: 161, name: "Porradakome", region: "Serra", images: [] },
  { id: 162, name: "Lumeorito", region: "Serra", images: [] },
  { id: 163, name: "Extrateroide", displayName: "ExtraterÃ³ide", region: "Serra", images: [] },
  { id: 164, name: "Rosurubu", region: "Serra", images: [] },
  { id: 165, name: "Glamurubu", region: "Serra", images: [] },
  { id: 166, name: "Capelodio", displayName: "CapelÃ³dio", region: "Lendas", images: [] },
  { id: 167, name: "Cuiapim", region: "Lendas", images: [] },
  { id: 168, name: "Negagua", displayName: "NegaguÃ¡", region: "Lendas", images: [] },
  { id: 169, name: "Lobizarro", region: "Lendas", images: [{ src: "assets/bixos/lobizarro.png", label: "Padrao" }] },
  { id: 170, name: "Curupirio", region: "Feito por Humanos", images: [] },
  { id: 171, name: "Friguica", displayName: "FriguiÃ§a", region: "Pré-Históricos", images: [] },
  { id: 172, name: "Geloterio", displayName: "GelotÃ©rio", region: "Pré-Históricos", images: [] },
  { id: 173, name: "Tigrarisco", region: "Pré-Históricos", images: [] },
  { id: 174, name: "Sabreletrico", displayName: "SabrelÃ©trico", region: "Pré-Históricos", images: [] },
  { id: 175, name: "Gliptolito", region: "Pré-Históricos", images: [] },
  { id: 176, name: "Rochedonte", region: "Pré-Históricos", images: [] },
  { id: 177, name: "Gigaboia", displayName: "GigabÃ³ia", region: "Pré-Históricos", images: [] },
  { id: 178, name: "Tokantita", displayName: "TokantitÃ£", region: "Pré-Históricos", images: [] },
  { id: 179, name: "Rola-sol", region: "Lendários", subtitle: "Estrela do Norte", images: [] },
  { id: 180, name: "Sucurimensa", region: "Lendários", subtitle: "Correnteza do Norte", images: [] },
  { id: 181, name: "Tuiutrovao", displayName: "TuiÃºtrovÃ£o", region: "Lendários", subtitle: "Tormenta do Norte", images: [] },
  { id: 182, name: "Sincorvina", region: "Stand By", subtitle: "Corrente do Norte", images: [] },
  { id: 183, name: "Mapinguru", region: "Stand By", images: [] }
];

